### PR TITLE
Remove npm peer dependency

### PR DESCRIPTION
**Pull request by kemitchell**

### CODE REVIEW

**Comment by anseljh** [comment]
I'm a little slow, so you're going to have to be patient with me and explain peer dependencies again... I even went to a NodeJS packaging talk today and asked the speaker, and he didn't understand them! :grimacing:

**Comment by kemitchell** [comment]
The upshot is that you should avoid using them, in keeping with the spirit of this PR :smile: 

Isaac, original author of npm, has written a few great comments on the subject:

https://github.com/npm/npm/issues/5080#issuecomment-40545599

https://github.com/npm/npm/issues/5080#issuecomment-40551620

**Comment by anseljh** [comment]
So would anything happen if we removed all these?

https://github.com/search?q=peerdependencies+commonform&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by kemitchell** [comment]
I removed the peer dependency from level-commonform and commonform-analyze. The other packages are the peer dependencies themselves.

**Comment by kemitchell** [comment]
Using npm version 3 or greater, the difference with whether or not `npm install` shows a warning.

**Pull request merged**
